In [8]:
import pandas as pd

In [10]:
#Los datos se pueden capturar desde excel (csv, xlsx), bases de datos o de un servidor
datos = pd.read_csv('C:/Users/Santiago HG/Desktop/Programas Python Coursera/Forbes.csv')
datos.head()

,Company,Sector,Industry,Continent,Country,Market Value,Sales,Profits,Assets,Rank,Forbes Webpage
0,ICBC,Financials,Major Banks,Asia,China,215.6,148.7,42.7,3124.9,1,http://www.forbes.com/companies/icbc/
1,China Construction Bank,Financials,Regional Banks,Asia,China,174.4,121.3,34.2,2449.5,2,http://www.forbes.com/companies/china-construc...
2,Agricultural Bank of China,Financials,Regional Banks,Asia,China,141.1,136.4,27.0,2405.4,3,http://www.forbes.com/companies/agricultural-b...
3,JPMorgan Chase,Financials,Major Banks,North America,United States,229.7,105.7,17.3,2435.3,4,http://www.forbes.com/companies/jpmorgan-chase/
4,Berkshire Hathaway,Financials,Investment Services,North America,United States,309.1,178.8,19.5,493.4,5,http://www.forbes.com/companies/berkshire-hath...

In [11]:
datos

,Company,Sector,Industry,Continent,Country,Market Value,Sales,Profits,Assets,Rank,Forbes Webpage
0,ICBC,Financials,Major Banks,Asia,China,215.6,148.7,42.7,3124.9,1,http://www.forbes.com/companies/icbc/
1,China Construction Bank,Financials,Regional Banks,Asia,China,174.4,121.3,34.2,2449.5,2,http://www.forbes.com/companies/china-construc...
2,Agricultural Bank of China,Financials,Regional Banks,Asia,China,141.1,136.4,27.0,2405.4,3,http://www.forbes.com/companies/agricultural-b...
3,JPMorgan Chase,Financials,Major Banks,North America,United States,229.7,105.7,17.3,2435.3,4,http://www.forbes.com/companies/jpmorgan-chase/
4,Berkshire Hathaway,Financials,Investment Services,North America,United States,309.1,178.8,19.5,493.4,5,http://www.forbes.com/companies/berkshire-hath...
...,...,...,...,...,...,...,...,...,...,...,...
1995,Cameco,Materials,Diversified Metals & Mining,North America,Canada,9.5,2.4,0.3,7.6,1996,http://www.forbes.com/companies/cameco/
1996,BMCE Bank,Financials,Regional Banks,Africa,Morocco,4.6,1.5,0.1,26.3,1997,http://www.forbes.com/companies/bmce-banque-ma...
1997,Synovus Financial,Financials,Regional Banks,North America,United States,3.4,1.2,0.2,26.2,1998,http://www.forbes.com/companies/synovus-financ...
1998,Equifax,Consumer Discretionary,Business & Personal Services,North America,United States,8.5,2.3,0.3,4.5,1999,http://www.forbes.com/companies/equifax/
1999,UNY Group Holdings,Consumer Discretionary,Specialty Stores,Asia,Japan,1.4,10.7,0.1,8.8,1999,http://www.forbes.com/companies/uny-group-hold...

In [12]:
print(datos[:6])

                      Company      Sector              Industry  \
0                        ICBC  Financials           Major Banks
1     China Construction Bank  Financials        Regional Banks
2  Agricultural Bank of China  Financials        Regional Banks
3              JPMorgan Chase  Financials           Major Banks
4          Berkshire Hathaway  Financials   Investment Services
5                 Exxon Mobil      Energy  Oil & Gas Operations

       Continent        Country  Market Value  Sales  Profits  Assets  Rank  \
0           Asia          China         215.6  148.7     42.7  3124.9     1
1           Asia          China         174.4  121.3     34.2  2449.5     2
2           Asia          China         141.1  136.4     27.0  2405.4     3
3  North America  United States         229.7  105.7     17.3  2435.3     4
4  North America  United States         309.1  178.8     19.5   493.4     5
5  North America  United States         422.3  394.0     32.6   346.8     6

                                      Forbes Webpage
0              http://www.forbes.com/companies/icbc/
1  http://www.forbes.com/companies/china-construc...
2  http://www.forbes.com/companies/agricultural-b...
3    http://www.forbes.com/companies/jpmorgan-chase/
4  http://www.forbes.com/companies/berkshire-hath...
5       http://www.forbes.com/companies/exxon-mobil/

In [13]:
print(datos.loc[0])

Company                                            ICBC
Sector                                       Financials
Industry                                    Major Banks
Continent                                          Asia
Country                                           China
Market Value                                      215.6
Sales                                             148.7
Profits                                            42.7
Assets                                           3124.9
Rank                                                  1
Forbes Webpage    http://www.forbes.com/companies/icbc/
Name: 0, dtype: object

In [14]:
print(datos[["Company", "Sales"]])

                         Company  Sales
0                           ICBC  148.7
1        China Construction Bank  121.3
2     Agricultural Bank of China  136.4
3                 JPMorgan Chase  105.7
4             Berkshire Hathaway  178.8
...                          ...    ...
1995                      Cameco    2.4
1996                   BMCE Bank    1.5
1997           Synovus Financial    1.2
1998                     Equifax    2.3
1999          UNY Group Holdings   10.7

[2000 rows x 2 columns]

In [15]:
print("La suma total de las compañias es: ", sum(datos["Sales"]))

La suma total de las compañias es:  38360.99999999978